export class GenAIRuleGenerator {
  private fieldTypes = {
    fullName: 'string',
    email: 'string', 
    phone: 'string',
    address: 'string',
    emailDomain: 'string',
    duplicateEmailCount: 'number',
    duplicatePhoneCount: 'number',
    nameSimilarityScore: 'number',
    atsScore: 'number',
    roleRelevanceScore: 'number',
    'exactMatches.length': 'number',
    'fuzzyMatches.length': 'number'
  };

  private validOperators = {
    string: ['equals', 'not_equals', 'contains', 'regex'],
    number: ['equals', 'not_equals', 'greater_than', 'less_than', 'in_range']
  };

  generateRule(adminIntent: string): any {
    const intent = adminIntent.toLowerCase().trim();
    console.log('Processing admin intent:', intent);
    
    // Duplicate email detection
    if (intent.includes('duplicate') && intent.includes('email')) {
      return this.createRule('EMAIL_DUPLICATE', 'Duplicate Email Detection', 
        'Flags applications using an email already present in the system',
        [{ field: 'duplicateEmailCount', operator: 'greater_than', value: 0, weight: 1 }],
        55, 2);
    }

    // Suspicious email patterns
    if (intent.includes('suspicious') && intent.includes('email')) {
      return this.createRule('EMAIL_PATTERN', 'Suspicious Email Pattern',
        'Detects random or autogenerated email patterns',
        [{ field: 'email', operator: 'regex', value: '^[a-z0-9]{8,}@', weight: 1 }],
        35, 3);
    }

    // Disposable email domains
    if (intent.includes('disposable') || intent.includes('temp')) {
      return this.createRule('DISPOSABLE_EMAIL', 'Disposable Email Domain',
        'Flags applications using disposable email services',
        [{ field: 'email', operator: 'regex', value: '@(tempmail|guerrillamail|10minutemail|mailinator)', weight: 1 }],
        45, 2);
    }

    // Name similarity - enhanced matching
    if ((intent.includes('similar') || intent.includes('same')) && intent.includes('name')) {
      return this.createRule('NAME_SIMILARITY', 'High Name Similarity',
        'Flags applications with highly similar names',
        [{ field: 'nameSimilarityScore', operator: 'greater_than', value: 0.85, weight: 1 }],
        40, 4);
    }

    // Low ATS score
    if (intent.includes('low') && intent.includes('ats')) {
      return this.createRule('LOW_ATS', 'Low ATS Resume Score',
        'Flags resumes that are not ATS optimized',
        [{ field: 'atsScore', operator: 'less_than', value: 70, weight: 1 }],
        30, 5);
    }

    // Duplicate phone
    if (intent.includes('duplicate') && intent.includes('phone')) {
      return this.createRule('PHONE_DUPLICATE', 'Duplicate Phone Detection',
        'Flags applications using the same phone number',
        [{ field: 'duplicatePhoneCount', operator: 'greater_than', value: 0, weight: 1 }],
        50, 2);
    }

    // Multiple exact matches
    if (intent.includes('multiple') && intent.includes('exact')) {
      return this.createRule('MULTIPLE_EXACT', 'Multiple Exact Matches',
        'Flags applications with multiple exact field matches',
        [{ field: 'exactMatches.length', operator: 'greater_than', value: 1, weight: 1 }],
        65, 1);
    }

    // Enhanced pattern matching for common intents
    if (intent.includes('find') || intent.includes('detect') || intent.includes('flag')) {
      if (intent.includes('name')) {
        return this.createRule('NAME_SIMILARITY', 'Name Similarity Detection',
          'Detects similar applicant names',
          [{ field: 'nameSimilarityScore', operator: 'greater_than', value: 0.8, weight: 1 }],
          35, 4);
      }
      if (intent.includes('email')) {
        return this.createRule('EMAIL_DUPLICATE', 'Email Duplication Check',
          'Detects duplicate email addresses',
          [{ field: 'duplicateEmailCount', operator: 'greater_than', value: 0, weight: 1 }],
          50, 2);
      }
    }

    // Default fallback with better naming
    console.log('Using fallback rule for intent:', intent);
    return this.createRule('GENERAL_RISK', 'General Risk Detection',
      `Custom rule based on: ${adminIntent}`,
      [{ field: 'exactMatches.length', operator: 'greater_than', value: 0, weight: 1 }],
      25, 10);
  }

  private createRule(type: string, name: string, description: string, conditions: any[], score: number, priority: number): any {
    return {
      ruleId: `RULE_${type}_${Date.now()}`,
      name,
      description,
      conditions,
      logic: 'AND',
      score,
      priority,
      isActive: true,
      version: 1,
      createdBy: 'AI'
    };
  }

  validateRule(rule: any): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check required fields
    if (!rule.ruleId) errors.push('Rule ID is required');
    if (!rule.name) errors.push('Rule name is required');
    if (!rule.description) errors.push('Rule description is required');
    if (rule.score === undefined || rule.score === null) errors.push('Rule score is required');
    if (!rule.conditions || rule.conditions.length === 0) {
      errors.push('At least one condition is required');
    }

    // Validate conditions
    rule.conditions?.forEach((condition: any, index: number) => {
      const fieldType = this.fieldTypes[condition.field as keyof typeof this.fieldTypes];
      
      if (!fieldType) {
        errors.push(`Invalid field: ${condition.field}`);
        return;
      }

      const validOps = this.validOperators[fieldType as keyof typeof this.validOperators];
      if (!validOps.includes(condition.operator)) {
        errors.push(`Invalid operator '${condition.operator}' for ${fieldType} field '${condition.field}'`);
      }
    });

    return { valid: errors.length === 0, errors };
  }
}