export class GenAIRuleGenerator {
  private fieldTypes = {
    fullName: 'string',
    email: 'string', 
    phone: 'string',
    address: 'string',
    emailDomain: 'string',
    duplicateEmailCount: 'number',
    duplicatePhoneCount: 'number',
    nameSimilarityScore: 'number',
    atsScore: 'number',
    roleRelevanceScore: 'number',
    'exactMatches.length': 'number',
    'fuzzyMatches.length': 'number'
  };

  private validOperators = {
    string: ['equals', 'not_equals', 'contains', 'regex'],
    number: ['equals', 'not_equals', 'greater_than', 'less_than', 'in_range']
  };

  generateRule(adminIntent: string): any {
    const intent = adminIntent.toLowerCase();
    
    // Duplicate email detection
    if (intent.includes('duplicate') && intent.includes('email')) {
      return {
        ruleId: `RULE_EMAIL_DUPLICATE_${Date.now()}`,
        name: 'Duplicate Email Detection',
        description: 'Flags applications using an email already present in the system',
        conditions: [{
          field: 'duplicateEmailCount',
          operator: 'greater_than',
          value: 0,
          weight: 1
        }],
        logic: 'AND',
        score: 55,
        priority: 2,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Suspicious email patterns
    if (intent.includes('suspicious') && intent.includes('email')) {
      return {
        ruleId: `RULE_EMAIL_PATTERN_${Date.now()}`,
        name: 'Suspicious Email Pattern',
        description: 'Detects random or autogenerated email patterns',
        conditions: [{
          field: 'email',
          operator: 'regex',
          value: '^[a-z0-9]{8,}@',
          weight: 1
        }],
        logic: 'AND',
        score: 35,
        priority: 3,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Disposable email domains
    if (intent.includes('disposable') || intent.includes('temp')) {
      return {
        ruleId: `RULE_DISPOSABLE_EMAIL_${Date.now()}`,
        name: 'Disposable Email Domain',
        description: 'Flags applications using disposable email services',
        conditions: [{
          field: 'email',
          operator: 'regex',
          value: '@(tempmail|guerrillamail|10minutemail|mailinator)',
          weight: 1
        }],
        logic: 'AND',
        score: 45,
        priority: 2,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Name similarity
    if (intent.includes('similar') && intent.includes('name')) {
      return {
        ruleId: `RULE_NAME_SIMILARITY_${Date.now()}`,
        name: 'High Name Similarity',
        description: 'Flags applications with highly similar names',
        conditions: [{
          field: 'nameSimilarityScore',
          operator: 'greater_than',
          value: 0.85,
          weight: 1
        }],
        logic: 'AND',
        score: 40,
        priority: 4,
        isActive: true,
        version: 1,
        createdBy: 'AI',
        explanation: 'Applicant name is very similar to an existing application'
      };
    }

    // Low ATS score
    if (intent.includes('low') && intent.includes('ats')) {
      return {
        ruleId: `RULE_LOW_ATS_${Date.now()}`,
        name: 'Low ATS Resume Score',
        description: 'Flags resumes that are not ATS optimized',
        conditions: [{
          field: 'atsScore',
          operator: 'less_than',
          value: 70,
          weight: 1
        }],
        logic: 'AND',
        score: 30,
        priority: 5,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Duplicate phone
    if (intent.includes('duplicate') && intent.includes('phone')) {
      return {
        ruleId: `RULE_PHONE_DUPLICATE_${Date.now()}`,
        name: 'Duplicate Phone Detection',
        description: 'Flags applications using the same phone number',
        conditions: [{
          field: 'duplicatePhoneCount',
          operator: 'greater_than',
          value: 0,
          weight: 1
        }],
        logic: 'AND',
        score: 50,
        priority: 2,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Multiple exact matches
    if (intent.includes('multiple') && intent.includes('exact')) {
      return {
        ruleId: `RULE_MULTIPLE_EXACT_${Date.now()}`,
        name: 'Multiple Exact Matches',
        description: 'Flags applications with multiple exact field matches',
        conditions: [{
          field: 'exactMatches.length',
          operator: 'greater_than',
          value: 1,
          weight: 1
        }],
        logic: 'AND',
        score: 65,
        priority: 1,
        isActive: true,
        version: 1,
        createdBy: 'AI'
      };
    }

    // Default fallback
    return {
      ruleId: `RULE_CUSTOM_${Date.now()}`,
      name: 'Custom Rule',
      description: 'Custom fraud detection rule',
      conditions: [{
        field: 'exactMatches.length',
        operator: 'greater_than',
        value: 0,
        weight: 1
      }],
      logic: 'AND',
      score: 25,
      priority: 10,
      isActive: true,
      version: 1,
      createdBy: 'AI'
    };
  }

  validateRule(rule: any): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check required fields
    if (!rule.ruleId) errors.push('Rule ID is required');
    if (!rule.name) errors.push('Rule name is required');
    if (!rule.description) errors.push('Rule description is required');
    if (rule.score === undefined || rule.score === null) errors.push('Rule score is required');
    if (!rule.conditions || rule.conditions.length === 0) {
      errors.push('At least one condition is required');
    }

    // Validate conditions
    rule.conditions?.forEach((condition: any, index: number) => {
      const fieldType = this.fieldTypes[condition.field as keyof typeof this.fieldTypes];
      
      if (!fieldType) {
        errors.push(`Invalid field: ${condition.field}`);
        return;
      }

      const validOps = this.validOperators[fieldType as keyof typeof this.validOperators];
      if (!validOps.includes(condition.operator)) {
        errors.push(`Invalid operator '${condition.operator}' for ${fieldType} field '${condition.field}'`);
      }
    });

    return { valid: errors.length === 0, errors };
  }
}